services:
  database:
    image: mongo
    ports:
      - "27017:27017"
    restart: on-failure
    container_name: mongodb
    volumes:
      - whattodo_mongodb:/data
    networks:
      - app-network

  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    container_name: backend
    networks:
      - app-network
    env_file:
      - ./.env.local
    volumes:
      - ./app/backend:/app

  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    container_name: frontend
    networks:
      - app-network
    volumes:
      - ./app/frontend:/app
      - /app/node_modules/

volumes:
  whattodo_mongodb:
  node_modules:

networks:
  app-network:
    driver: bridge
